spring.application.name=academico-service

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.properties.hibernate.format_sql=true
# Timeout para o cliente Feign que acessa o aluno-service
# O nome "aluno-service" precisa bater com o name do @FeignClient
spring.cloud.openfeign.client.config.aluno-service.connect-timeout=2000
spring.cloud.openfeign.client.config.aluno-service.read-timeout=3000