server.port=${SERVER_PORT}

aluno.service.url=${ALUNO_SERVICE_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.h2.console.enabled=false

spring.cloud.openfeign.client.config.aluno-service.connectTimeout=${ALUNO_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.aluno-service.readTimeout=${ALUNO_READ_TIMEOUT:3000}